version: '3'
services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo

  mongo-test:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db-test

volumes:
  mongo-data:
    driver: local
