version: '3'
services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - URL_MONGO=mongodb://mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mongo
    volumes:
      - mongo-data:/data/db
      - ./mongo-seed/mongo-seed.js:/docker-entrypoint-initdb.d/mongo-seed.js

  mongo-test:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db-test
      - ./mongo-seed/mongo-test-seed.js:/docker-entrypoint-initdb.d/mongo-test-seed.js

volumes:
  mongo-data:
    driver: local
