version: 2

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d mongo-test
            npm install
            npm run test
            npm run lint
            npm run build
